version: "3.0"

networks:
  webservices:
    external: true

services:
  authelia:
    container_name: authelia
    image: docker.io/authelia/authelia:latest
    restart: unless-stopped
    networks:
      - webservices
    expose:
      - 9091
    environment:
      AUTHELIA_JWT_SECRET_FILE: /secrets/JWT_SECRET
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /secrets/STORAGE_ENCRYPTION_KEY
      TZ: Europe/Madrid
    volumes:
      - /opt/docker/authelia/config:/config
      - /opt/docker/authelia/secrets:/secrets
  # n8n:
  #   container_name: n8n
  #   image: docker.n8n.io/n8nio/n8n
  #   # restart: unless-stopped
  #   environment:
  #     # - PUID=1000
  #     # - PGID=1000
  #     - TZ=Europe/Madrid
  #     - DB_TYPE=sqlite
  #     - N8N_BASIC_AUTH_ACTIVE=true
  #     - N8N_BASIC_AUTH_USER=${N8N_AUTH_USER}
  #     - N8N_BASIC_AUTH_PASSWORD=${N8N_AUTH_PASSWORD}
  #     - N8N_HOST=${N8N_HOSTNAME}
  #     - N8N_PORT=5678
  #     # - WEBHOOK_URL=https://${N8N_HOSTNAME}/
  #     - N8N_PERSONALIZATION_ENABLED=false
  #     - N8N_DIAGNOSTICS_ENABLED=false
  #     - GENERIC_TIMEZONE=Europe/Madrid
  #     - EXECUTIONS_MODE=regular
  #     - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
  #     - EXECUTIONS_DATA_SAVE_ON_ERROR=all # save failed runs
  #     - EXECUTIONS_DATA_PRUNE=true
  #     - EXECUTIONS_DATA_PRUNE_MAX_COUNT=1000
  #     # - EXECUTIONS_DATA_MAX_AGE=168 # Prune 7 days (hours)
  #   volumes:
  #     - /opt/docker/n8n/data:/home/node/.n8n
  #   networks:
  #     - webservices
